### ISSUE TITLE
Onboarding Marijn

### ISSUE THREAD

**Issue by KleinJonasUVT** [KleinJonasUVT/tilburg.ai#1]
**Goal of this issue**
Onboard @marijnbransen1998 to Tilburg.ai, ensuring he is familiar with the necessary resources and arranging a meeting with @KleinJonasUVT, @marijnbransen1998 and @MatthijsvanGils for a comprehensive introduction and discussion on task communication.

**Resources**
- Onboarding guide: [Tilburg Science Hub Onboarding](https://github.com/tilburgsciencehub/onboarding)
- Guide on making contributions: [How to Make Contributions to Tilburg.ai](https://tilburg.ai/how-to-make-contributions-to-tilburg-ai/)

**Deliverables**
- [x] Ensure @marijnbransen1998 reads the provided onboarding guide.
- [x] Familiarize @marijnbransen1998 with the process of writing articles for Tilburg.ai.
- [x] Schedule a meeting involving @marijnbransen1998, @KleinJonasUVT, and @MatthijsvanGils to discuss onboarding specifics and communication strategies for task management.

**Comment by MatthijsvanGils** [comment]
Every deliverable has been met
